### ISSUE TITLE
Error running example files

### ISSUE THREAD

**Issue by danylmc** [csoneson/ARMOR#100]
Running Ubuntu 18.04. Snakemake and conda installed. I get the following error running the sample data: 

EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.3a
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.1a

**Comment by csoneson** [comment]
It looks like the `STAR` index was generated with an old version of `STAR`. Did you update the version of `STAR` in `ARMOR`, or point to an existing `STAR` index?

**Comment by danylmc** [comment]
It was just pointing to the index in the example_data folder. I uninstalled and reinstalled STAR, and ran the index build again and it's working fine. Thanks!

**Comment by csoneson** [comment]
Great that this was solved. Just a note that there is no `STAR` index in a clean download of the `ARMOR` example data (https://github.com/csoneson/ARMOR/tree/master/example_data), so I'm guessing that this was generated with a previous version of `ARMOR`. Generally, we recommend not updating the software versions in the middle of an analysis, since it can have unintended consequences (see https://github.com/csoneson/ARMOR/wiki/Managing-multiple-projects).
