### ISSUE TITLE
issue when setting up and running the example data

### ISSUE THREAD

**Issue by pikkaa215** [csoneson/ARMOR#105]
I was trying to set up the ARMOR workflow on server with conda 4.10.0, Ubuntu 18.04.5 and snakemake installed, and it seems that some packages were missing. I tried to install them manually but I was not authorized to do so. Any idea on how to solve this? 

ERROR: dependencies ‘AnnotationDbi’, ‘RSQLite’, ‘biomaRt’ are not available for package ‘GenomicFeatures’

ERROR: dependencies ‘GenomicFeatures’, ‘RSQLite’, ‘AnnotationDbi’ are not available for package ‘ensembldb’

ERROR: dependencies ‘ExperimentHub’, ‘AnnotationHub’, ‘AnnotationDbi’, ‘ensembldb’, ‘GenomicFeatures’ are not available for package ‘scRNAseq’
* removing 
ERROR: dependencies ‘AnnotationDbi’, ‘GenomicFeatures’, ‘ensembldb’, ‘BiocFileCache’, ‘AnnotationHub’ are not available for package ‘tximeta’
* removing 

The downloaded source packages are in
	‘/tmp/RtmpD8embR/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
tximeta : failed to installError in FUN(X[[i]], ...) : there is no package called ‘tximeta’
Calls: usePackage ... suppressPackageStartupMessages -> withCallingHandlers -> lapply -> FUN
In addition: There were 22 warnings (use warnings() to see them)
Execution halted

**Comment by sorjuela** [comment]
Hi @pikkaa215,

Yes, we also see this same issue in the latest GitHub Action only for ubuntu https://github.com/csoneson/ARMOR/actions/runs/755054578 

The problem seems to be in the installation of RSQLite, which is also reported as an issue in their repo: https://github.com/r-dbi/RSQLite/issues/367

We are trying to figure out a solution. Thanks for reporting :)

Stephany

**Comment by fhaertner** [comment]
Hey,

in the meantime, until the issue is resolved, you can install an older version of  RSQLite. In the 'scripts/install_pkgs.R' file just add the following lines in the usePackage() function before the other packages are installedd with BiocManager:

`## Install the other packages
    install.packages("remotes", repos = "http://cran.rstudio.com/",
                         lib = .libPaths()[1])
	remotes::install_version("RSQLite", version = "2.2.5", dependencies = TRUE,
						repos = "http://cran.rstudio.com/", lib = .libPaths()[1],
						Ncpus = as.integer(ncores))
    
    isInstalled <- pkgs %in% installed.packages(lib.loc = .libPaths()[1])[, 1]
    BiocManager::install(pkgs[!isInstalled],
                         update = FALSE, dependencies = TRUE,
                         lib = .libPaths()[1], Ncpus = as.integer(ncores))`

You can also have a look here:
https://stackoverflow.com/questions/67279457/error-with-r-package-biomart-and-this-dependency-rsqlite

**Comment by csoneson** [comment]
Thanks, and sorry for the lack of updates here, we're still working on clearing our Ubuntu/conda GitHub Actions run. Actually I had hoped that `RSQLite` version 2.2.7 would solve the issues that were present in version 2.2.6 (and thus would not require manually installing version 2.2.5)... 🤔

**Comment by sorjuela** [comment]
Hi,

We have a workaround for this issue in the `fixbuilderror` branch:  https://github.com/csoneson/ARMOR/tree/fixbuilderror  which should work now for ubuntu machines. Please let us know if this solves your issue, or if you need help using this branch.

**Comment by pikkaa215** [comment]
Yes. That solved my problem. Thanks!
