### ISSUE TITLE
Gencode / Ensembl

### ISSUE THREAD

**Issue by ms-gx** [csoneson/ARMOR#92]
I am a bit confused regarding parameters in the `Reference annotation details`-Section of `config.yaml`:
1) What does Ensembl vs Gencode mean? What is its influence on the analysis?
2) Why does one even have to provide `organism`, `build` and `release`? My GTF is depending on an denovo assembly of the transcriptome which got merged with an already existing annotation of the genome.

My organism is Apis mellifera and I the annotation and the genome assembly is fetched from NCBI (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/254/395/GCF_003254395.2_Amel_HAv3.1). How do I have to set the parameters in this case?

**Comment by sorjuela** [comment]
Hi,

The ARMOR pipeline is a reference-based analysis. We require the specification of Ensembl/Gencode so that the workflow knows how to properly parse the annotation files. 

You can read about the difference between these two here: https://www.gencodegenes.org/pages/faq.html . Additionally, Gencode is only for Human and Mouse

In your data, the annotation is not only reference based, but has additional features from the de-novo assembly. We cannot guarantee that the parsing will be done properly, and you might lose information.

You should be able to run the pipeline anyway (or at least try it out). The idea of specifying all the annotation details is to keep track of them. You would have to set the annotation as `Ensembl`, and your organism as `Apis_mellifera`. I imagine `HAv3.1` is the `build`, and the `version` should be in the link you sent, however these shouldn't affect the analysis.

You should also set `run_camera` as `False`.

**Comment by csoneson** [comment]
I'm going to close this issue - feel free to reopen if there are remaining problems.

**Comment by ms-gx** [comment]
Sorry for no response. I did not get it to run through but did not investigate further.

**Comment by csoneson** [comment]
Ok. Let us know if we can do something to help (if so, please provide the error message that you get, and check whether the example data set runs through, to see whether it is an explicit problem related to the data, or a more general setup problem).

**Comment by ms-gx** [comment]
Setup worked fine. The problem was somehow related to the fact that I was not analysing mouse/human data and the format/id or similar was not as expected by your toolchain. Next time I access the system I run it on I might quickly report back to you.
